### ISSUE TITLE
How to use qbws? example please

### ISSUE THREAD

**Issue by Code-Crash** [johnballantyne/qbws#7]
Hi @johnballantyne ,

I understand that this QBWS will help me to create my SOAP API's in node or js.

I don't have much idea about QuickBooks and QuickBooks web connector, but I want to implement the sync functionality from my server to QuickBooks desktop.

So I understand that I need to set up the QuickBooks web connector on local system where the QuickBooks file is present but I don't know how to use QBWS with nodejs, can you please provide the example how to authenticate or how to get all the customer just a snippet, this will help me a lot.

Thanks.

**Comment by brandonros** [comment]
@Code-Crash We might have to try to figure this out together.

Here is what I have so far:

run test/client.js

open QuickBooks Web Connector

import the .qwc file this package comes with

pray

**Comment by brandonros** [comment]
I can't prove that this package is forwarding requests to the WebConnector, or doing anything at all.

I have high hopes though.

**Comment by brandonros** [comment]
Ok. Now I think I have it totally wrong. You have to import the .qwc file into QuickBooks Web Connector, and QWC will run the script every 2 minutes.

Where the output goes? Let's see...

**Comment by brandonros** [comment]
@johnballantyne I see that you are still slightly active.

Here is what is currently happening:

Everything works great, except:

"QuickBooks found an error when parsing the provided XML text stream"

I've tried all kinds of things like:

encoding

qbXML version

different queries

I'm running QuickBooks Pro 2016 and QuickBooks Web Connector 2.1.0.30. I wonder if that is it?

**Comment by johnballantyne** [comment]
I've only ever used qbws with QuickBooks Desktop 2014, I don't have access to a 2016 license to verify unfortunately. I will clear some time later this week to check on this and see if I can help; at the very least maybe we can figure out if it is indeed a version issue.

**Comment by Code-Crash** [comment]
Hi @brandonros,
Sorry for delay response, I will try this today and let's see if we can figure out something.

thanks @johnballantyne, Please have a look in 2016 version, I also have the same.

**Comment by Code-Crash** [comment]
Thanks, @brandonros. It's working now.

I'm running the nodejs on mac and by using the virtual box I'm using the windows with QuickBooks and QuickBooks web connector with .qwc file.

You have any idea how we can utilize this for multiple companies?

**Comment by johnballantyne** [comment]
@Code-Crash I'm glad you got it working, what did you do differently?

For multiple companies, you should create a database of usernames, passwords, and company file locations and keep track of session tickets. This should all be handled when you call [`authenticate()`](https://github.com/johnballantyne/qbws/blob/master/docs/qbws-api.md#authenticate--string--array).

**Comment by Code-Crash** [comment]
@johnballantyne Thanks :)
