### ISSUE TITLE
Could not start QuickBooks.

### ISSUE THREAD

**Issue by Code-Crash** [johnballantyne/qbws#9]
Hi @johnballantyne ,

`node test/client.js`

When I'm running this project by `node client.js`, I'm getting this working fine for a first time with authentication and all the request is also done.

but after that it's giving me the error `Could not start QuickBooks.` after authentication:

```
WebMethod: authenticate() has been called by QBWebConnector
    Parameters received:
        string strUserName = Admin
        string strPassword = Admin
    Password locally stored = Admin
    Return values:
        string[] authReturn[0] = 2b0e7d30-b580-11e6-b7d0-6bd4c65bd962
        string[] authReturn[1] = C:\Users\Public\Documents\Intuit\QuickBooks\Company Files\Test Sample\Test Sample.qbw
WebMethod: connectionError() has been called by QBWebConnector
    Parameters received:
        string ticket = 2b0e7d30-b580-11e6-b7d0-6bd4c65bd962
        string hresult = 0x80040408
        string message = Could not start QuickBooks.
    HRESULT = 0x80040408
    Message = Could not start QuickBooks.
    Sending DONE to stop.
    Return values:
        string retVal = DONE
```

Do you have any idea, why this is giving me this error?

**Comment by johnballantyne** [comment]
Do you have QuickBooks open?

**Comment by Code-Crash** [comment]
Yes. I have restarted the system but its still giving me the same error.

**Comment by johnballantyne** [comment]
I've never encountered this error, so I can only take shots in the dark unfortunately. When you set up the Application Certificate, did you allow access when QuickBooks is not running? See [here](http://stackoverflow.com/a/15822232/1832306)

**Comment by Code-Crash** [comment]
@johnballantyne Yes, I allow the Web Connector application to access QuickBooks if the QuickBooks is not opened also.

But still the same.

So, for now, I'm using 30 days trial version, I don't think so this is an issue.

Just have a look if you can found this. :) 

Thanks
